category:   5
name_pt:    Irmão Do Jorel E O Incrível Array
name_en:    Jorel's Brother And The Amazing Array
name_es:    Jorel's Brother And The Amazing Array
subject_pt: matemática, vetor e matriz
subject_en: mathematics, array
subject_es: 
level:      3
timelimit:  1